KCFloatingActionButton/KCFloatingActionButton.swift

Basically just wrapping the Open\Close so nothing really happens when it's clicked.
In the case of no items I left the closed state always false... I think that makes more sense?
Would help us out over here! :)

Prevent overlay\animations from happening if there are no child items

---

KCFloatingActionButton/KCFloatingActionButton.swift
Sample/KCFloatingActionButton/ViewController.swift

ViewController의 서브뷰에 액션버튼을 추가했을 경우
버튼 외 영역을 터치하면 버튼만 사라져야 하는데 밑에 깔린 테이블뷰나 TextField가 동작합니다.
그래서 layer대신 UIControl로 전체를 덮어서 다른 이벤트가 동작하지 않게 했습니다.

use a UIControl to stop event propagation instead of overlay layer

---

KCFloatingActionButton/KCFloatingActionButton.swift
KCFloatingActionButton/KCFloatingActionButtonDelegate.swift
Sample/KCFloatingActionButton-Sample.xcodeproj/project.pbxproj

Created a delegate protocol that can be expanded upon to include a bunch of additional events related to the behavior of the FAB. Right now it only contains a function that notifies the delegate when a user has tapped on a FAB that does not contain any defined sub items.
Not all FABs need to have nested child actions, so this is good for the user case where an app needs a FAB that represents just a single primary action.

Defined an optional FAB delegate.

---

KCFloatingActionButton/KCFloatingActionButton.swift
KCFloatingActionButton/KCFloatingActionButtonItem.swift

- Use plusLayer color to tint custom images when used
- When using custom image instead of default plus image, rotate it as you would plusLayer
- Specify rotation degrees in IB
- Set child item image tint separately in IB. Default to plusColor when itemImageColor is left blank
- Auto-close items on item tap. Customizable in IB.
- Syntax updates for Swift 2.2

Various changes/additions

---

KCFloatingActionButton/KCFloatingActionButton.swift

Corrected a bug where FAB button delegates were incorrectly using strong references instead of weak.

Changed FAB delegate to weak.

---

KCFloatingActionButton/KCFloatingActionButton.swift

This avoids side effects when calling the hitTest without actually tapping a button (i.e. in UI automation). It does not seem to change the component's behaviour under the assumption that, when you set autoCloseOnTap to false, the component does not have to handle closing in any case.
I propose this change because right now the component cannot be used by our test automation framework, but also because the way hitTest: is used in the component does not follow the expectations one might have when using this method.
I hope you can incorporate this change in a future version of your component. It's of great use in general!

Removed closing the FAB from the hitTest method

---

KCFloatingActionButton/KCFloatingActionButton.swift

With the default location of the frame, the button is now tappable until the right and rightbottom of the screen. This prevents tapping behind it by accident.

Made tapping more user friendly with button in bottom right of screen

---

Sources/KCFloatingActionButton.swift

Items are misaligned horizontally when using `openAnimationType = .slideDown`:
Removing the line `item.frame.origin.x = 4` from `slideDownAnimationWithOpen()` fixes the issue for me:

Fix .slideDown horizontal item misalignment

---

Sources/KCFloatingActionButton.swift

Don't move the keyboard when the sticky property is set to true.

Respect sticky property when showing/hiding keyboard

---

Sources/KCFloatingActionButton.swift

This fixes a bug that would remove the overlay after opening the menu if the menu was closed and opened in quick succession.
The issue is that if the menu is `open()`'ed before the `UIView.animate` closing animation completes, the `UIView.animate` `completion` block will be executed after the menu has been opened again. Thus the overlay will be removed from the open menu. 
Removing the overlay for an open menu produces two annoying effects:
1) The background is clearly visible, instead of being darkened by the overlay.
2) Tapping the background does not close the menu, as the tap gesture is tied to the overlay.
There might be a better way to do this, but it worked for me. :)

fix overlay animation bug when opening/closing in quick succession

---

Sources/KCFloatingActionButton.swift

M_PI is deprecated in Xcode 8.3

Replace M_PI with Double.pi

---

Sources/Floaty.swift

This is useful when using the Floaty in a view controller on the iPad,
where you don't always want the overlay to cover the entire screen.
There is no change in behaviour when using FloatyManager.
Only affects Floaty view's added to a view manually.

Overlay view frame now adopts Floaty's superview bounds.

---

Sources/Floaty.swift

According to Apple Docs:
UIKeyboardFrameBeginUserInfoKey- The key for an NSValue object containing a CGRect that identifies the start frame of the keyboard in screen coordinates.
UIKeyboardFrameEndUserInfoKey - The key for an NSValue object containing a CGRect that identifies the end frame of the keyboard in screen coordinates.
https://developer.apple.com/documentation/uikit/uiwindow/keyboard_notification_user_info_keys

issue #170: Floaty moves with keyboard only at first time, iOS 11

---

Sources/Floaty.swift

Changes made to meet WCAG A guidelines for Accessibility #182 
This change creates a transparent view with accessible values to it to exist along with the FloatyItems.  Added are passthrough methods for accessibilityLabel, accessibilityHint and accessibilityValue.
Ideally, accessibilityValue would be along the lines of "Opened" and "Closed", however translated versions of that text is pretty much out of scope for this. 
FloatyItems with a title are basically accessible. (They do not have the button state added to the titleLabel, however, I'd rather feedback on how much extra work a user would need to make it more properly accessible.
Current code I use to make the items properly accessible: 
```
//FloatyItem with only an image needs all its accessible element set
let item = …
```

Change to meet basic Accessiblity guidelines 

---

Sources/Floaty.swift

When Floaty button is bigger than its items and .slideDown animation is used first item overlaps the Floaty button. This is because items views are top aligned with the Floaty button.

Fixing .slideDown open type

---

Sources/Floaty.swift

As a part of the changes to support Swift 4.2 the open and close functions found inside the Floaty class were switched from being scoped as open to being scoped as public. This breaks any implementations where a developer may have chosen to sub-class the Floaty implementation and override these methods. A potential use case being the one mentioned in [#234](https://github.com/kciter/Floaty/issues/234) where a developer may wish to call the handler of the FloatyItem when only one FloatyItem is present rather than showing that single item and requiring the user to tap it. 
```
import Floaty
class CustomFloaty: Floaty {
override fun open() {
if self.items.count == 1 {
let item = self.items[0]
item.handler?(item)
} else {
super.open()
}
}
}
```
This is my first pull request so I apologize if …

Making Floaty open/close functions accessible for override

---

Sources/Floaty.swift

There is a bug with show/hide keyboard. You can reproduce it in demo project. Open the app, button is relative to Safe Area. Tap in textfield, then tap outside of keyboard. Button is not relative to safe area, because safeAreaInsets.bottom is 0 at that moment.
Also, I have added relativeToSafeArea property for those cases, when it is not required to place button relative to safe area.

Fix Safe Area insets

---

Floaty.xcodeproj/project.pbxproj
Sources/Floaty.swift
Sources/FloatyDelegate.swift

This PR adds two items:
Can be used for FABs with one item which should be directly opened, instead of opening a menu. For example:
```
import Floaty
class ViewController: UIViewController {
// ...
func setupFloaty() {
let floaty = Floaty()
floaty.fabDelegate = self
floaty.addItem("Add", icon: nil) { item in
// Do something
}
view.addSubview(floaty)
}
}
extension ViewController: FloatyDelegate {
func floatyShouldOpen(_ floaty: Floaty) -> Bool {
guard floaty.items.count == 1, let item = floaty.items.first, let handler = item.handler
else { return true }
handler(item)
return false
}
}
```
Can be used for the same goal as 1, without the need of implementing a delegate method. For example:
```
import Floaty
class ViewController: UIViewController {
// ...
func setupFloaty() {
let floaty = …
```

Floaty shouldOpen/shouldClose handlers and bool to handle first item directly

---

Sources/Floaty.swift
Sources/FloatyDelegate.swift

Implemented horizontal support for one of the animations. The rest can be implemented easily by the ones who want to support.
Added support for disabling close by tapping on overlay. Used for popover tables. When tapped they were closing the floaty first.

Partial horizontal support and prevent close on overlay tap option

---

Sources/FloatyItem.swift

According to https://github.com/realm/SwiftLint/issues/2395, it is better not to declare it as a free function.
This is spotted by linter rules and I'd like to propose this fix to make the code taste better. 😄

Fix: Limit the scope of operator

---

Sources/Floaty.swift

The TAB keep crash due to the `buttonImageView = UIImageView(image: buttonImage)` trigger `draw(_:)` so the app running in the infinite loop on the macOS.
Bring the `buttonImageView` reset code before `setNeedsDisplay` fix it. And iOS/iPadOS and macOS all works

Fix crash issue on iPad for macOS and macCatalyst

---

Sources/Floaty.h
Sources/FloatyManager.swift
Sources/FloatyViewController.swift
Sources/FloatyWindow.swift

I found some old references to `KCFloatingActionButton` naming on class docs so I changed them to the new `Floaty` naming.

Changing class docs to remove references of old naming
