kciter/Floaty

KCFloatingActionButton/KCFloatingActionButton.swift
KCFloatingActionButton/KCFloatingActionButtonItem.swift
Sample/KCFloatingActionButton/ViewController.swift

Hello,
I've create two properties on the item class: circleShadowColor and titleShadowColor to manage different color and address it independently.
There is another propertie on the button itself called itemShadowColor that represent a default color for the two properties

Expose shadow property

---

KCFloatingActionButton/KCFloatingActionButtonItem.swift

made it not stretch it as much and centered

Better loading of image

---

KCFloatingActionButton/KCFloatingActionButton.swift

Added speed variable to button pop animations. Fixes #43

Added speed variable to button pop animations

---

Sources/KCFloatingActionButton.swift
Sources/KCFloatingActionButtonItem.swift

Add KCFABOpenAnimationType 'slideDown' and @property to change Color in itemButton

New Add KCFABOpenAnimationType

---

Sources/KCFloatingActionButtonItem.swift

Hi
When I would like to change color of icon. I can't do that because the lib didn't have function. So I add more feature to your lib. It's ok to use it and I would like to share them. It's work for icon only. I attached image result to you.
Best regards,
Chawatvish Worrapoj
image result -> 
[https://www.dropbox.com/s/sj1z3jww7q1sfq6/17156082_10158410747840327_3558802528940718760_n.jpg?dl=0](url)

Add function change tint color of icon image.

---

Sample/KCFloatingActionButton-Sample.xcodeproj/project.pbxproj
Sample/KCFloatingActionButton/TableViewController.swift
Sample/KCFloatingActionButton/ViewController.swift
Sources/Floaty.swift
Sources/FloatyItem.swift

한국분이 만드신 라이브러리였군요. 대단하세요!
왼쪽에 floaty를 놓고 싶을 때가 있어서 enum으로 넣어보았습니다.
감사히 잘쓰고 있습니다~ :)

Add titleLabelPosition property to set title label's position

---

Sample/KCFloatingActionButton/TableViewController.swift
Sample/KCFloatingActionButton/ViewController.swift
Sources/Floaty.swift
Sources/FloatyDelegate.swift

floatyWillOpen
floatyDidOpen
floatyWillClose
floatyDidClose
This fixes https://github.com/kciter/Floaty/issues/126

Add detailed delegate methods

---

Sources/FloatyItem.swift

Fixes https://github.com/kciter/Floaty/issues/135

Re-center image view after changing imageSize

---

Sources/Floaty.swift

Introduce a variable `respondsToKeyboard` that determines whether Floaty responds to keyboard notifications

added responds to keyboard var

---

Sources/Floaty.swift

fix an issue where floaty would not adjust to layout changes

---

Sources/Floaty.swift

This way items can have individual shadows.

floaty shadow effects all items

---

Sources/FloatyManager.swift

Fixed crash on font from [#176](https://github.com/kciter/Floaty/issues/176)

crash on font - fixed

---

Sources/Floaty.swift

See #156, based on the work of @kh0r. Would be great if this could be merged

iPhone X support

---

Sources/Floaty.swift

Allows to set the default button shadow color

Button shadow color property

---

Sources/Floaty.swift

hello, 
thank you for your job.
I've added a simple management of selected button color (when user tapped). The default is the same color of 'buttonColor', otherwise get the color (with IBDesignable).
thanks again
best,

- selected color button

---

Sources/Floaty.swift

Makes the settings visible in the Storyboard

To fix the invisible settings in the Storyboard

---

Floaty.xcodeproj/project.pbxproj
Sample/KCFloatingActionButton-Sample.xcodeproj/project.pbxproj
Sample/KCFloatingActionButton/ViewController.swift
Sources/Floaty.swift
Sources/UIView+Draggable.swift

Add dragging option to the menu button because sometimes it hides content.

Add draggable menu button option

---

README.md

This PR replaces readme cocoapods quotes for single quotes.

Replace Cocoapods quotes in readme

---

README.md

Xcode suggested these fixes when I pasted in the example.

Tiny documentation updates for Swift 4

---

Package.swift
README.md

- Add Package.swift to support SPM
- Update Readme

Add SPM support

---

Sources/Floaty.swift

Made the highlighted color of the button settable. Defaults to old behaviour.
Private tintLayer is now added below the icon image view.

Settable highlighted color

---

Sample/KCFloatingActionButton/CircularAnimationViewController.swift
Sources/FloatyItem.swift

Sample code for top and bottom title in circle animator VC

Add top and bottom for menu items title for circular animation
